sudo: required
services:
  - docker

before_install:
  - docker build -t rochimartinelli/docker-react -f Dockerfile.dev .

script: 
  - docker run rochimartinelli/docker-react npm test -- --coverage 
